services:
  - type: web
    name: roleta-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
  bash .render/install_chrome.sh
  pip install -r requirements.txt
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    runtime:
      pythonVersion: 3.11
